In [ ]:
## Problem Statement 1: Write a Python program to multiply a 𝑀 × 𝑁 matrix by 𝑁 × 𝐴 matrix and create a real matrix product.

In [2]:
import numpy as np

In [42]:
M=int(input("enter the value of M:"))

N=int(input("enter the value of N:"))

A=int(input("enter the value of A:"))


A1=np.random.randint(10,size=(M,N))
print("First array A1:\n", A1)

B1=np.random.randint(10,size=(N,A))
print("Second array B1:\n",B1)

C=np.dot(A1,B1)
print("Dot product of A1 and B1 array is:\n", C)

enter the value of M:5
enter the value of N:3
enter the value of A:2
First array A1:
 [[0 8 3]
 [2 3 6]
 [4 6 1]
 [8 6 1]
 [0 0 7]]
Second array B1:
 [[3 4]
 [7 7]
 [9 3]]
Dot product of A1 and B1 array is:
 [[83 65]
 [81 47]
 [63 61]
 [75 77]
 [63 21]]


In [ ]:
##Problem Statement 2: Write a NumPy program to check if each element of an array of yourchoice is composed of digits, lower case letters, and upper case letters only.

In [37]:
Originalarray= np.array(["Ankit","rrr","KGF","34","RRR","ankit","78"])
print("Original array is:\n")
print(Originalarray)

Original array is:

['Ankit' 'rrr' 'KGF' '34' 'RRR' 'ankit' '78']


In [5]:
## Lower case only
print("Lower case only:\n")
print(np.char.islower(Originalarray))

Lower case only:

[False  True False False False  True False]


In [43]:
## Upper case only
print("Upper case only:\n")
print(np.char.isupper(Originalarray))

Upper case only:

[False False  True False  True False False]


In [44]:
## Digits only
print("Digits only:\n")
print(np.char.isdigit(Originalarray))

Digits only:

[False False False  True False False  True]


In [ ]:
##Problem Statement 3: Write a program that reads two space-separated positive integers 𝑋 and 𝑌 as input and perform the following tasks:

In [14]:
##1.Create a list (lst1) starting at one (1) with 16 elements at a step of X
X,Y=input().split(sep=",")
print("Value of X:\n",X)
print("Value of Y:\n",Y)
lst1=[]
for i in range (1,200,int(X)):
    lst1.append(i)
    if len(lst1)>15:
        print("Required lst1 with step X is:\n",lst1)
        break
        
##2.Create a list (lst2) starting at one (1) with 16 elements at a step of Y
lst2=[]
for i in range (1,200,int(Y)):
    lst2.append(i)
    if len(lst2)>15:
        print("Required lst2 with step Y is:\n",lst2)
        break

4,7
Value of X:
 4
Value of Y:
 7
Required lst1 with step X is:
 [1, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61]
Required lst2 with step Y is:
 [1, 8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99, 106]


In [15]:
##3.Create two NumPy arrays np1 and np2 using lst1 and lst2 respectively.
import numpy as np

np1=np.array(lst1)
print("Numpy Array np1 by using lst1 is:\n",np1)

np2=np.array(lst2)
print("Numpy Array np2 by using lst2 is:\n",np2)

Numpy Array np1 by using lst1 is:
 [ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61]
Numpy Array np2 by using lst2 is:
 [  1   8  15  22  29  36  43  50  57  64  71  78  85  92  99 106]


In [16]:
##4.Reshape both the NumPy arrays to (4,4)
Array1=np1.reshape(4,4)
print("Array1 obtained by reshape np1 is:\n",Array1)

Array2=np2.reshape(4,4)
print("Array2 obtained by reshape np2 is:\n",Array2)

Array1 obtained by reshape np1 is:
 [[ 1  5  9 13]
 [17 21 25 29]
 [33 37 41 45]
 [49 53 57 61]]
Array2 obtained by reshape np2 is:
 [[  1   8  15  22]
 [ 29  36  43  50]
 [ 57  64  71  78]
 [ 85  92  99 106]]


In [17]:
##5.Create a new np array (np3) with values obtained by subtracting both the arrays (np1 -np2)
np3=Array1-Array2
print("new np array np3 is:\n",np3)

new np array np3 is:
 [[  0  -3  -6  -9]
 [-12 -15 -18 -21]
 [-24 -27 -30 -33]
 [-36 -39 -42 -45]]


In [18]:
##6.Print all the elements of np3 in a single dimension list 
list1=np3.ravel()
print("all the elements of np3 in a single dimension list:\n",list1)

all the elements of np3 in a single dimension list:
 [  0  -3  -6  -9 -12 -15 -18 -21 -24 -27 -30 -33 -36 -39 -42 -45]


In [ ]:
##Problem Statement 4: Write a python program that takes two integer numpy array,P and Q of shape[3*3] and perform the following taks:
##Print the element wise difference of matrix P and Q.

In [11]:
P=np.array([[23,45,44],[34,22,67],[12,89,55]])
print("Array P is:\n",P)

Q=np.array([[12,40,24],[1,19,57],[22,79,25]])
print("Array Q is:\n",Q)

print("Element wise difference of matrix P and Q is:")
print(P-Q)

Array P is:
 [[23 45 44]
 [34 22 67]
 [12 89 55]]
Array Q is:
 [[12 40 24]
 [ 1 19 57]
 [22 79 25]]
Element wise difference of matrix P and Q is:
[[ 11   5  20]
 [ 33   3  10]
 [-10  10  30]]
