In [2]:
!pip install numpy

In [1]:
import numpy as np 

In [7]:
a=np.arange(20,29).reshape(3,3)
b=np.arange(30,39).reshape(3,3)
print(a)
print(b)
np.stack((a,b))

[[20 21 22]
 [23 24 25]
 [26 27 28]]
[[30 31 32]
 [33 34 35]
 [36 37 38]]


array([[[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38]]])

In [8]:
np.hstack((a,b))

array([[20, 21, 22, 30, 31, 32],
       [23, 24, 25, 33, 34, 35],
       [26, 27, 28, 36, 37, 38]])

In [9]:
np.vstack((a,b))

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38]])

In [10]:
np.concatenate((a,b))

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38]])

In [11]:
np.concatenate((a,b),axis=0)

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38]])

In [13]:
z= np.concatenate((a,b),axis=1)
print(z)

[[20 21 22 30 31 32]
 [23 24 25 33 34 35]
 [26 27 28 36 37 38]]


In [15]:
np.hsplit(z,2)

[array([[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]]),
 array([[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38]])]

In [16]:
np.vsplit(z,3)

[array([[20, 21, 22, 30, 31, 32]]),
 array([[23, 24, 25, 33, 34, 35]]),
 array([[26, 27, 28, 36, 37, 38]])]

In [24]:
a=np.arange(8)
print(a)
print(np.split(a,2))
a[6]

[0 1 2 3 4 5 6 7]
[array([0, 1, 2, 3]), array([4, 5, 6, 7])]


6

In [35]:
a=np.arange(16).reshape(4,4)
print(a)
np.hsplit(a,2)
print(a[1,1])
print(a[3,3])
print(a[2,1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
5
15
9


In [51]:
a[1:2,2:4]

array([[5]])

In [36]:
a[2:4,2:4]

array([[10, 11],
       [14, 15]])

In [37]:
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [38]:
a[0:2,2:4]

array([[2, 3],
       [6, 7]])

In [46]:
a=np.arange(9).reshape(3,3)
b=np.arange(20,29).reshape(3,3)
print(a)
print(b)
print(np.row_stack((a,b)))
print(np.column_stack((a,b)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[20 21 22]
 [23 24 25]
 [26 27 28]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [20 21 22]
 [23 24 25]
 [26 27 28]]
[[ 0  1  2 20 21 22]
 [ 3  4  5 23 24 25]
 [ 6  7  8 26 27 28]]


In [54]:
a=np.array([1,2,3,4,5,6,7,8,9])
a[1]
a[3]

4

In [56]:
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [57]:
a[1:3,0:2]

array([[3, 4],
       [6, 7]])

In [58]:
a[0,1]

1

In [59]:
a[0:3,1:2]

array([[1],
       [4],
       [7]])