In [1]:
## Numpy install check
!pip install numpy

In [39]:
import numpy as np

In [13]:
(dir(np))## features of numpy
len(dir(np))

608

In [3]:
## create a simple numpy array
a=[1,2,3,4,5,6]
print(type(a))
n=np.array(a) 
print(n)
type(n)

<class 'list'>
[1 2 3 4 5 6]


numpy.ndarray

In [17]:
a=(1,2,3,4,5,6)
print(type(a))
n=np.array(a) 
print(n)
type(n)

<class 'tuple'>
[1 2 3 4 5 6]


numpy.ndarray

In [18]:
a={1,2,3,4,5,6}
print(type(a))
n=np.array(a) 
print(n)
type(n)

<class 'set'>
{1, 2, 3, 4, 5, 6}


numpy.ndarray

In [19]:
 a={'a':1,'b':2,'c':3}
print(type(a))
n=np.array(a) 
print(n)
type(n)

<class 'dict'>
{'a': 1, 'b': 2, 'c': 3}


numpy.ndarray

In [2]:
##creating array from random numbers of any size
##numpy.random.randint(low, high=None, size=None, dtype=’l’)
##random is a function, doing random sampling in numpy.
import numpy as np
array=np.random.randint(10,size=(20))
array

array([3, 1, 2, 0, 1, 7, 1, 1, 8, 0, 8, 2, 9, 1, 0, 8, 9, 8, 6, 7])

In [3]:
##1st argument --> numbers ranging from 0 to 9, 
# 2nd argument, row = 2, col = 3
array = np.random.randint(10, size=(2, 3))
print(array)

[[8 4 5]
 [4 3 0]]


In [21]:
## attributes of nd array 
a=[1,2,3,4,5,6]
print(type(a))

n=np.array(a) 
print(n)
type(n)

print("............. attributes.........")
print(n.size)## no of elements

print(n.shape)## (6 rows no column )

print(n.dtype)## data type

print(n.ndim)## dimension of array here is one 

print(n.itemsize)## bytes used to store each element

<class 'list'>
[1 2 3 4 5 6]
............. attributes.........
6
(6,)
int32
1
4


In [31]:
a=[10,20,30,40,50,60,70,80,'an']## data type of entire array will become character 
print(type(a))

n=np.array(a) 
print(n)
print(type(n))

print("............. attributes.........")
print(n.size)## no of elements

print(n.shape)## (6 rows no column )

print(n.dtype)## data type, small ndn<11 characters and big ndn > 11character

print(n.ndim)## dimension of array here is one 

print(n.itemsize)## bytes used to store each element

<class 'list'>
['10' '20' '30' '40' '50' '60' '70' '80' 'an']
<class 'numpy.ndarray'>
............. attributes.........
9
(9,)
<U11
1
44


In [33]:
## 2d array
a=[[1,2,3],[4,5,6],[7,8,9]]
print(type(a))
n=np.array(a)
print(n)
print(type(n))

print("............. attributes.........")
print(n.size)## no of elements

print(n.shape)## (6 rows no column )

print(n.dtype)## data type, small ndn<11 characters and big ndn > 11character

print(n.ndim)## dimension of array here is one 

print(n.itemsize)## bytes used to store each element

<class 'list'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
............. attributes.........
9
(3, 3)
int32
2
4


In [34]:
## 2d array
a=[[1,2,3],[4,5,6],[7,8,9],['ankit','jyoti','nishu']]
print(type(a))
n=np.array(a)
print(n)
print(type(n))

print("............. attributes.........")
print(n.size)## no of elements

print(n.shape)## (6 rows no column )

print(n.dtype)## data type, small ndn<11 characters and big ndn > 11character

print(n.ndim)## dimension of array here is one 

print(n.itemsize)## bytes used to store each element

<class 'list'>
[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']
 ['ankit' 'jyoti' 'nishu']]
<class 'numpy.ndarray'>
............. attributes.........
12
(4, 3)
<U11
2
44


In [41]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
##np.arange(start,stop,step)
np.arange(20,28)

array([20, 21, 22, 23, 24, 25, 26, 27])

In [48]:
np.arange(45,55,2)

array([45, 47, 49, 51, 53])

In [51]:
##np.linspace(start,stop, no of equally spaced elements you want between start and stop)
np.linspace(1,25,5)

array([ 1.,  7., 13., 19., 25.])

In [52]:
np.linspace(1,30,6)

array([ 1. ,  6.8, 12.6, 18.4, 24.2, 30. ])

In [70]:
## copy: to create a distinct copy of a array at different location
a=np.array([1,2,3,4,5])
print(a)
print(id(a))
b=np.array([1,2,3,4,5])
print(b)
print(id(b))
c=a ## a is copy to c,by this any changes in a will cause the same in c.

print(c)
print(id(c))

d=a.copy()
print(id(d)) 
print(d)

[1 2 3 4 5]
621514586416
[1 2 3 4 5]
621514586992
[1 2 3 4 5]
621514586416
621514586320
[1 2 3 4 5]


In [71]:
print(d)

[1 2 3 4 5]


In [87]:
## reshape: change the appearance or shape of an array
##resize : change the original array
a=np.array([21,22,23,24,25,26,27,28,29])
print(a)
print(a.reshape(3,3))## change the shape of a.
print(a.shape)
print(a)
print('............................')
print(a.resize(3,3)) ## permanently change the original array.
print(a.shape)
print(a)


[21 22 23 24 25 26 27 28 29]
[[21 22 23]
 [24 25 26]
 [27 28 29]]
(9,)
[21 22 23 24 25 26 27 28 29]
............................
None
(3, 3)
[[21 22 23]
 [24 25 26]
 [27 28 29]]


In [65]:
## arthmetic operators
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])
print(a+b)
print(a-b)
print(a*b)
print(b/a)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[0.1 0.1 0.1 0.1]


In [23]:
## Matrix product
## row of first must be equal to column of second matrix
a=np.arange(0,9).reshape(3,3)
b=np.ones((3,3))
print(a)
print(b)
print(np.dot(a,b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]


In [88]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)
b=a.reshape(3,3)
print(b)
c=np.arange(10,19).reshape(3,3)
print(c)
print(np.dot(b,c))


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [25]:
np.sqrt([1,4,9,16,25,36,49])

array([1., 2., 3., 4., 5., 6., 7.])

In [27]:
## (np.mod, gives the reminder)
print(np.arange(7))
np.mod(np.arange(7),(3))##[1/3=1]

[0 1 2 3 4 5 6]


array([0, 1, 2, 0, 1, 2, 0], dtype=int32)

In [28]:
np.log([1,2,3,4,5])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [29]:
##Aggregate functions
a=np.array([1,2,3,4,5,6,7,8,9])
print(a.sum())
print(a.min())
print(a.max())
print(a.mean())
print(a.std())## standard deveation

45
1
9
5.0
2.581988897471611


In [31]:
#Logical function (check true or false value)
## all check if  all are false
np.all([False])

False

In [32]:
np.all([True])

True

In [33]:
np.all([False, True])

False

In [34]:
np.all([-3,4,5,-6])## No 0 is here so it is true

True

In [35]:
np.all([-4,5,0,4],) ## 0 is for false

False

In [40]:
np.array([[True, False], [True, True],[True, False]])

array([[ True, False],
       [ True,  True],
       [ True, False]])

In [120]:
## axis= 0 means column wise and axis= 1 means row wise
np.all(np.array([[False, True],[False, True],[True,False]]),axis=0)

array([False, False])

In [121]:
np.all(np.array([[False, True],[True, True],[True,True]]),axis=0)

array([False,  True])

In [122]:
np.all(np.array([[False, True],[False, True],[True,False]]),axis=1)

array([False, False, False])

In [89]:
np.all(np.array([[False, True, True],[True,False,True],[True,True,True]]))

False

In [90]:
np.all(np.array([[False, True, True],[True,False,True],[True,True,True]]),axis=1)

array([False, False,  True])

In [100]:
np.all(np.array([[False, True, True],[True,False,True],[True,True,True]]),axis=0)

array([False, False,  True])

In [39]:
np.all(np.array([[False, True],[False, True]]),axis=1)

array([False, False])

In [92]:
##np.any (check for is any true and if there is atleast one true then output will also be true)
np.any([1,2,3,5])

True

In [93]:
np.any([1,2,3,5,0])

True

In [94]:
np.any([1,0,0,0,0])

True

In [95]:
np.any([0,0,0,0,0])

False

In [96]:
np.any([True,False,True])

True

In [97]:
np.any([True,False,False])

True

In [98]:
np.any(np.array([[True,False,False],[False,False,False]]))

True

In [99]:
np.any(np.array([[True,False,False],[False,False,False]]),axis=1)

array([ True, False])

In [101]:
np.any(np.array([[True,False,False],[False,False,False]]),axis=0)

array([ True, False, False])

In [ ]:
##logic function

In [42]:
x=np.array([0,1,2,3,4])
print(np.logical_and(x>1 ,x<4))
print(np.logical_or(x>1 ,x<4))
print(np.logical_not(x>1 ,x<4))

[False False  True  True False]
[ True  True  True  True  True]
[ True  True False False False]


In [57]:
##indexing
arr=np.arange(21,26)
print(arr)
arr[0]
arr[-5]
arr[1:3]
print(arr[1:3])
print(arr[-4:-2])

[21 22 23 24 25]
[22 23]
[22 23]


In [61]:
##2d indexing
arr=np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [62]:
## 0
arr[0,0]

0

In [63]:
arr[2,0]

6

In [65]:
arr[0,2]

2

In [66]:
arr[2,2]

8

In [67]:
arr[2,2]

8

In [72]:
## multiple elements
#arr[:,:]
arr[0:2,0:2]

array([[0, 1],
       [3, 4]])

In [79]:
arr[1:3,1:2]

array([[4],
       [7]])

In [86]:
arr[0:2,1:3]

array([[1, 2],
       [4, 5]])

In [95]:
## Aray transformation
##ravel - 3d to 2d
arr=np.arange(21,30).reshape(3,3)
arr.ravel()

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [101]:
arr.transpose()

array([[21, 24, 27],
       [22, 25, 28],
       [23, 26, 29]])

In [102]:
##concatinate
a=np.arange(21,30).reshape(3,3)
print(a)
b=np.arange(51,60).reshape(3,3)
print(b)

[[21 22 23]
 [24 25 26]
 [27 28 29]]
[[51 52 53]
 [54 55 56]
 [57 58 59]]


In [103]:
np.concatenate((a,b))## default coloumn wise add


array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [104]:
np.concatenate((a,b), axis=0) ##coloumn wise add

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [105]:
np.concatenate((a,b), axis=1) ## row wise add

array([[21, 22, 23, 51, 52, 53],
       [24, 25, 26, 54, 55, 56],
       [27, 28, 29, 57, 58, 59]])

In [106]:
##STACK
np.stack((a,b))

array([[[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]]])

In [107]:
np.column_stack((a,b)) ## column wise

array([[21, 22, 23, 51, 52, 53],
       [24, 25, 26, 54, 55, 56],
       [27, 28, 29, 57, 58, 59]])

In [108]:
np.row_stack((a,b))## row wise

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [109]:
np.hstack((a,b))

array([[21, 22, 23, 51, 52, 53],
       [24, 25, 26, 54, 55, 56],
       [27, 28, 29, 57, 58, 59]])

In [110]:
np.vstack((a,b))

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [114]:
### split
x=np.arange(8)
print(x)
#np.split(x,3)
np.split(x,2)

[0 1 2 3 4 5 6 7]


[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

In [118]:
##hsplit= cut it in vertical and pullling the split parts in right and left
a= np.arange(16).reshape((4,4))
print(a)
np.hsplit(a,2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [119]:
##vsplit= cut it in horizontally and pullling the split parts in up and down
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [3]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [4]:
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
np.mod(a,2)

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [20]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
b=np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
np.concatenate((a,b))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
np.concatenate((a,b),axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [24]:
np.column_stack((a,b))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [25]:
np.row_stack((a,b))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
np.hstack((a,b))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [28]:
np.vstack((a,b))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
a=[1,2,3,4,5,6]
w=np.array(a)
print(w.ndim)
print(np.logical_and(w<3,w<9))
print(np.logical_or(w<3,w<9))
print(np.logical_not(w<1,w>4))

1
[ True  True False False False False]
[ True  True  True  True  True  True]
[ True  True  True  True  True  True]
