In [ ]:
#pandas: is a libary used to deal with tabular data for data manupulation
## name pandas is derived from panel data
## there are two type of data structure used in pandas:1. Series 2. Data Frame

In [2]:
## series: one-d labled array
import pandas as pd
sr=pd.Series([1,2,3,4,5])
sr
##0,1,2,3,4 is indexig and 1,2,3,4,5 are values

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
## we can also give customize indexing as our requirements
sr=pd.Series([1,2,3,4,5],index=[10,20,30,40,50])
sr

10    1
20    2
30    3
40    4
50    5
dtype: int64

In [7]:
dct={"Ankit":45,"Nishu":55,"Jyoti":39}
pd.Series((dct),index=(["Ankit","Nishu","Jyoti"]))

Ankit    45
Nishu    55
Jyoti    39
dtype: int64

In [8]:
sr=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
sr

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [18]:
data=[1,2,3,4,5]##it can be list, tuple, set,dict and numpy array
sr=pd.Series(data)
sr

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [19]:
##tuple
data=(1,2,3,4,5)
sr=pd.Series((data), index=[10,20,30,40,50])
sr

10    1
20    2
30    3
40    4
50    5
dtype: int64

In [2]:
import pandas as pd
data={1,2,3,4,5}
sr=pd.Series((data), index=['a','b','c','d','e'])
sr

TypeError: 'set' type is unordered

In [3]:
## numpay array 1-d
import numpy as np
arr=np.array([1,2,3,4,5])
sr=pd.Series(arr)
sr

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [37]:
arr=np.array([1,2,3,4,5])
print(arr)
sr=pd.Series(arr, index=[10,20,30,40,50])
sr

[1 2 3 4 5]


10    1
20    2
30    3
40    4
50    5
dtype: int32

In [6]:
##2-d numpy array, it will not work because series take only 1-d data.
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
sr=pd.Series(arr)
sr

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


ValueError: Data must be 1-dimensional

In [39]:
## Data Frame are 2-d labled array
arr=np.arange(9).reshape(3,3)
print(arr)
df=pd.DataFrame(arr)
print(df)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
   0  1  2
0  0  1  2
1  3  4  5
2  6  7  8


In [40]:
## coustomize indexing
arr=np.arange(9).reshape(3,3)
print(arr)
df=pd.DataFrame(arr,index=[1,2,3]) ## index only name the rows
print(df)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
   0  1  2
1  0  1  2
2  3  4  5
3  6  7  8


In [49]:
arr=np.arange(9).reshape(3,3)
print(arr)
df=pd.DataFrame(arr,columns=[1,2,3]) ## colums only name the columns
df

[[0 1 2]
 [3 4 5]
 [6 7 8]]


1  2  3
0  0  1  2
1  3  4  5
2  6  7  8

In [48]:
arr=np.arange(9).reshape(3,3)
print(arr)
df=pd.DataFrame(arr,index=['a','b','c'], columns=[1,2,3])
df

[[0 1 2]
 [3 4 5]
 [6 7 8]]


1  2  3
a  0  1  2
b  3  4  5
c  6  7  8

In [50]:
arr=np.arange(9).reshape(3,3)
print(arr)
df=pd.DataFrame(arr,index=['row1','row2','row3'], columns=[1,2,3])
df

[[0 1 2]
 [3 4 5]
 [6 7 8]]


1  2  3
row1  0  1  2
row2  3  4  5
row3  6  7  8

In [47]:
arr=np.arange(16).reshape(4,4)
print(arr)
df=pd.DataFrame(arr,index=['row1','row2','row3','row4'], columns=['col1','col2','col3','col4']) 
df

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15

In [51]:
import numpy as np
data=np.array([[1,2,3,4,5],[10,20,30,40,50]])
df=pd.DataFrame(data,index=['row1','row2'], columns=['col1', 'col2','col3','col4','col5'])
df

col1  col2  col3  col4  col5
row1     1     2     3     4     5
row2    10    20    30    40    50

In [3]:
import pandas as pd
df= pd.read_csv("C:/Users/Ankit Sharma/Desktop/python/mtcars.csv")
df

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [12]:
df= pd.read_excel("C:/Users/Ankit Sharma/Desktop/python/mtcars.xlsx")
df

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [66]:
df.head()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [67]:
df.tail()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  \
27    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.9   1   1     5   
28  Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5   
29    Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.5   0   1     5   
30   Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.6   0   1     5   
31      Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.6   1   1     4   

    carb  
27     2  
28     4  
29     6  
30     8  
31     2

In [68]:
##operations on dataframes
#1.Accessing any column of data
df.mpg

0     21.0
1     21.0
2     22.8
3     21.4
4     18.7
5     18.1
6     14.3
7     24.4
8     22.8
9     19.2
10    17.8
11    16.4
12    17.3
13    15.2
14    10.4
15    10.4
16    14.7
17    32.4
18    30.4
19    33.9
20    21.5
21    15.5
22    15.2
23    13.3
24    19.2
25    27.3
26    26.0
27    30.4
28    15.8
29    19.7
30    15.0
31    21.4
Name: mpg, dtype: float64

In [70]:
##2.Accessing multiple columns of data
df[["mpg","disp"]]

mpg   disp
0   21.0  160.0
1   21.0  160.0
2   22.8  108.0
3   21.4  258.0
4   18.7  360.0
5   18.1  225.0
6   14.3  360.0
7   24.4  146.7
8   22.8  140.8
9   19.2  167.6
10  17.8  167.6
11  16.4  275.8
12  17.3  275.8
13  15.2  275.8
14  10.4  472.0
15  10.4  460.0
16  14.7  440.0
17  32.4   78.7
18  30.4   75.7
19  33.9   71.1
20  21.5  120.1
21  15.5  318.0
22  15.2  304.0
23  13.3  350.0
24  19.2  400.0
25  27.3   79.0
26  26.0  120.3
27  30.4   95.1
28  15.8  351.0
29  19.7  145.0
30  15.0  301.0
31  21.4  121.0

In [74]:
df[["cyl","hp"]]

cyl   hp
0     6  110
1     6  110
2     4   93
3     6  110
4     8  175
5     6  105
6     8  245
7     4   62
8     4   95
9     6  123
10    6  123
11    8  180
12    8  180
13    8  180
14    8  205
15    8  215
16    8  230
17    4   66
18    4   52
19    4   65
20    4   97
21    8  150
22    8  150
23    8  245
24    8  175
25    4   66
26    4   91
27    4  113
28    8  264
29    6  175
30    8  335
31    4  109

In [76]:
df[["am","drat","qsec"]]

am  drat   qsec
0    1  3.90  16.46
1    1  3.90  17.02
2    1  3.85  18.61
3    0  3.08  19.44
4    0  3.15  17.02
5    0  2.76  20.22
6    0  3.21  15.84
7    0  3.69  20.00
8    0  3.92  22.90
9    0  3.92  18.30
10   0  3.92  18.90
11   0  3.07  17.40
12   0  3.07  17.60
13   0  3.07  18.00
14   0  2.93  17.98
15   0  3.00  17.82
16   0  3.23  17.42
17   1  4.08  19.47
18   1  4.93  18.52
19   1  4.22  19.90
20   0  3.70  20.01
21   0  2.76  16.87
22   0  3.15  17.30
23   0  3.73  15.41
24   0  3.08  17.05
25   1  4.08  18.90
26   1  4.43  16.70
27   1  3.77  16.90
28   1  4.22  14.50
29   1  3.62  15.50
30   1  3.54  14.60
31   1  4.11  18.60

In [77]:
df[["carb"]]

carb
0      4
1      4
2      1
3      1
4      2
5      1
6      4
7      2
8      2
9      4
10     4
11     3
12     3
13     3
14     4
15     4
16     4
17     1
18     2
19     1
20     1
21     2
22     2
23     4
24     2
25     1
26     2
27     2
28     4
29     6
30     8
31     2

In [79]:
##3. delete any column.
##df.drop('column name', axis='column')
df.drop('vs',axis='columns')

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  am  gear  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   1     4   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   1     4   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1     4   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   0     3   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0     3   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   0     3   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0     3   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   0     4   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   0     4   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   0     4   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   0     4   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0     3   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0     3   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0     3   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0     3   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0     3   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0     3   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1     4   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1     4   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1     4   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   0     3   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0     3   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0     3   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0     3   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0     3   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1     4   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   1     5   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1     5   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   1     5   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   1     5   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   1     5   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1     4   

    carb  
0      4  
1      4  
2      1  
3      1  
4      2  
5      1  
6      4  
7      2  
8      2  
9      4  
10     4  
11     3  
12     3  
13     3  
14     4  
15     4  
16     4  
17     1  
18     2  
19     1  
20     1  
21     2  
22     2  
23     4  
24     2  
25     1  
26     2  
27     2  
28     4  
29     6  
30     8  
31     2

In [83]:
df.drop('drat',axis='columns')
#to see first 5 elements then
df.drop('drat',axis='columns').head()

Unnamed: 0   mpg  cyl   disp   hp     wt   qsec  vs  am  gear  carb
0          Mazda RX4  21.0    6  160.0  110  2.620  16.46   0   1     4     4
1      Mazda RX4 Wag  21.0    6  160.0  110  2.875  17.02   0   1     4     4
2         Datsun 710  22.8    4  108.0   93  2.320  18.61   1   1     4     1
3     Hornet 4 Drive  21.4    6  258.0  110  3.215  19.44   1   0     3     1
4  Hornet Sportabout  18.7    8  360.0  175  3.440  17.02   0   0     3     2

In [84]:
df.drop('gear',axis='columns').head()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  carb
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     1
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     1
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     2

In [87]:
df.drop('wt',axis='columns').head()

Unnamed: 0   mpg  cyl   disp   hp  drat   qsec  vs  am  gear  carb
0          Mazda RX4  21.0    6  160.0  110  3.90  16.46   0   1     4     4
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  17.02   0   1     4     4
2         Datsun 710  22.8    4  108.0   93  3.85  18.61   1   1     4     1
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  19.44   1   0     3     1
4  Hornet Sportabout  18.7    8  360.0  175  3.15  17.02   0   0     3     2

In [90]:
##4.Access particular data
##df["column you want to accss"][row]
df['mpg'][1]

21.0

In [91]:
df['qsec'][23]

15.41

In [92]:
df['disp'][4]

360.0

In [13]:
##5.Replace the data
##df['column']['row']='data to be assign'
df['hp'][1]='11'
df.head()

C:\Users\Ankit Sharma\AppData\Local\Temp\ipykernel_2676\2764786025.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hp'][1]='11'


Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0   11  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [18]:
df['cyl'][3]=67
df.head()

C:\Users\Ankit Sharma\AppData\Local\Temp\ipykernel_2676\1334231063.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cyl'][3]=67


Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0   11  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4   67  258.0  110  3.08  3.215  19.44  30   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [20]:
df['drat'][2]=4
df

C:\Users\Ankit Sharma\AppData\Local\Temp\ipykernel_2676\1946898382.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['drat'][2]=4


Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0   11  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  4.00  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4   67  258.0  110  3.08  3.215  19.44  30   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [4]:
df['Unnamed: 0'][6]='ankit'
df

C:\Users\Ankit Sharma\AppData\Local\Temp\ipykernel_6060\4204807783.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Unnamed: 0'][6]='ankit'


Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6                 ankit  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [5]:
##Mazda RX4-replace
df['Unnamed: 0'][0]='New car'
df

C:\Users\Ankit Sharma\AppData\Local\Temp\ipykernel_6060\1931320818.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Unnamed: 0'][0]='New car'


Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0               New car  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6                 ankit  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [25]:
##6 check the greater and lesser data
df[df['wt']>3.5]


Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec vs  am  \
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84  0   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40  0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60  0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00  0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98  0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82  0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42  0   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87  0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41  0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05  0   0   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60  0   1   

    gear  carb  
6      3     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
21     3     2  
23     3     4  
24     3     2  
30     5     8

In [26]:
df[df['mpg']>17]

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0           Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1       Mazda RX4 Wag  21.0    6  160.0   11  3.90  2.875  17.02   0   1   
2          Datsun 710  22.8    4  108.0   93  4.00  2.320  18.61   1   1   
3      Hornet 4 Drive  21.4   67  258.0  110  3.08  3.215  19.44  30   0   
4   Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5             Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
7           Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8            Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9            Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10          Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
12         Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
17           Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18        Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19     Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20      Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
24   Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25          Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26      Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27       Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
29       Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
31         Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
12     3     3  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
29     5     6  
31     4     2

In [27]:
df[df["cyl"]>6]

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
3        Hornet 4 Drive  21.4   67  258.0  110  3.08  3.215  19.44  30   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   

    gear  carb  
3      3     1  
4      3     2  
6      3     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
28     5     4  
30     5     8

In [ ]:
##iloc and loc 

In [17]:
df.iloc[:,:]

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [28]:
df

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0   11  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  4.00  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4   67  258.0  110  3.08  3.215  19.44  30   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [29]:
##iloc and loc 
##iloc is used to access particular rows and columns together
df.iloc[ : , :]

col1  col2  col3  col4  col5
row1     1     2     3     4     5
row2    10    20    30    40    50

In [30]:
df.iloc[0:1,2:]

col3  col4  col5
row1     3     4     5

In [31]:
df.iloc[1: ,0:2]

col1  col2
row2    10    20

In [37]:
df.iloc[1:,1:4]

col2  col3  col4
row2    20    30    40

In [39]:
df.iloc[0:2,2:3]

col3
row1     3
row2    30

In [41]:
df.loc['row1':,'col2':]

col2  col3  col4  col5
row1     2     3     4     5
row2    20    30    40    50

In [44]:
df.loc['row1':'row2', 'col3':'col3']

col3
row1     3
row2    30

In [32]:
df
df.iloc[6:10,0:3]

Unnamed: 0   mpg  cyl
6  Duster 360  14.3    8
7   Merc 240D  24.4    4
8    Merc 230  22.8    4
9    Merc 280  19.2    6

In [39]:
df.loc[6:10,'Unnamed: 0':'cyl']

Unnamed: 0   mpg  cyl
6   Duster 360  14.3    8
7    Merc 240D  24.4    4
8     Merc 230  22.8    4
9     Merc 280  19.2    6
10   Merc 280C  17.8    6

In [40]:
df.iloc[6:10,4:8]

hp  drat    wt   qsec
6  245  3.21  3.57  15.84
7   62  3.69  3.19  20.00
8   95  3.92  3.15  22.90
9  123  3.92  3.44  18.30

In [41]:
df.loc[6:9,'hp':'qsec']

hp  drat    wt   qsec
6  245  3.21  3.57  15.84
7   62  3.69  3.19  20.00
8   95  3.92  3.15  22.90
9  123  3.92  3.44  18.30

In [44]:
df.loc[21:25,'mpg':'qsec']

mpg  cyl   disp   hp  drat     wt   qsec
21  15.5    8  318.0  150  2.76  3.520  16.87
22  15.2    8  304.0  150  3.15  3.435  17.30
23  13.3    8  350.0  245  3.73  3.840  15.41
24  19.2    8  400.0  175  3.08  3.845  17.05
25  27.3    4   79.0   66  4.08  1.935  18.90

In [45]:
df.iloc[21:26,0:8]

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec
21  Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87
22       AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30
23        Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41
24  Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05
25         Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90

In [50]:
df.drop('mpg',axis='columns').tail()

Unnamed: 0  cyl   disp   hp  drat     wt  qsec vs  am  gear  carb
27    Lotus Europa    4   95.1  113  3.77  1.513  16.9  1   1     5     2
28  Ford Pantera L    8  351.0  264  4.22  3.170  14.5  0   1     5     4
29    Ferrari Dino    6  145.0  175  3.62  2.770  15.5  0   1     5     6
30   Maserati Bora    8  301.0  335  3.54  3.570  14.6  0   1     5     8
31      Volvo 142E    4  121.0  109  4.11  2.780  18.6  1   1     4     2

In [52]:
df['hp'][2]=40
df.head()

C:\Users\Ankit Sharma\AppData\Local\Temp\ipykernel_2676\3750455224.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hp'][2]=40


Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0   11  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   40  4.00  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4   67  258.0  110  3.08  3.215  19.44  30   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [53]:
df['hp'][2]

40

In [54]:
df['drat'][21]

2.76

In [56]:
df['drat'][21]=3
df

C:\Users\Ankit Sharma\AppData\Local\Temp\ipykernel_2676\367609237.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['drat'][21]=3


Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0   11  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   40  4.00  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4   67  258.0  110  3.08  3.215  19.44  30   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  3.00  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [57]:
df["Unnamed: 0"][0]='New Car'
df.head()

C:\Users\Ankit Sharma\AppData\Local\Temp\ipykernel_2676\946822757.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Unnamed: 0"][0]='New Car'


Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0            New Car  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0   11  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   40  4.00  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4   67  258.0  110  3.08  3.215  19.44  30   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [58]:
df.loc[0:10,'Unnamed: 0':'Unnamed: 0']

Unnamed: 0
0             New Car
1       Mazda RX4 Wag
2          Datsun 710
3      Hornet 4 Drive
4   Hornet Sportabout
5             Valiant
6          Duster 360
7           Merc 240D
8            Merc 230
9            Merc 280
10          Merc 280C

In [59]:
df.iloc[0:11,0:1]

Unnamed: 0
0             New Car
1       Mazda RX4 Wag
2          Datsun 710
3      Hornet 4 Drive
4   Hornet Sportabout
5             Valiant
6          Duster 360
7           Merc 240D
8            Merc 230
9            Merc 280
10          Merc 280C

In [61]:
df.drop('Unnamed: 0',axis="columns").head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0   11  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   40  4.00  2.320  18.61   1   1     4     1
3  21.4   67  258.0  110  3.08  3.215  19.44  30   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [10]:
##adding new columns
df["newcol1"]=0
df.head()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0            New car  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  newcol1  (newcol1, newcol2)  
0     4        0                   0  
1     4        0                   0  
2     1        0                   0  
3     1        0                   0  
4     2        0                   0

In [79]:
df["new_col"]=df['gear']+df['am']
df.head()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0            New Car  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0   11  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   40  4.00  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4   67  258.0  110  3.08  3.215  19.44  30   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   Ankit  new_col  ankit  
0      4        5  17.46  
1      4        5  18.02  
2      1        5  19.61  
3      1        3  19.44  
4      2        3  17.02

In [82]:
df["ankit"]=df['am']+df['qsec']
df.head()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0            New Car  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0   11  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   40  4.00  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4   67  258.0  110  3.08  3.215  19.44  30   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   Ankit  new_col  ankit  
0      4        5  17.46  
1      4        5  18.02  
2      1        5  19.61  
3      1        3  19.44  
4      2        3  17.02

In [11]:
df.columns

Index([          'Unnamed: 0',                  'mpg',                  'cyl',
                       'disp',                   'hp',                 'drat',
                         'wt',                 'qsec',                   'vs',
                         'am',                 'gear',                 'carb',
                    'newcol1', ('newcol1', 'newcol2')],
      dtype='object')

In [69]:
df.columns=['Unnamed: 0', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear','Ankit']
df.head()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0            New Car  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0   11  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   40  4.00  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4   67  258.0  110  3.08  3.215  19.44  30   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   Ankit  
0      4  
1      4  
2      1  
3      1  
4      2

In [ ]:
##date: 18june

In [11]:
## Concatenation
import pandas as pd

In [6]:
employees1=pd.read_csv("C:/Users/Ankit Sharma/Desktop/python/employees1.csv")
employees2=pd.read_csv("C:/Users/Ankit Sharma/Desktop/python/employees2.csv")
service=pd.read_csv("C:/Users/Ankit Sharma/Desktop/python/service.csv")
print(employees1)
print(employees2)
print(service)

   EmpID   Name   Location  Age
0      1  Name1       Pune   35
1      2  Name2  Bangalore   30
2      3  Name3  Bangalore   45
3      4  Name4    Chennai   40
4      5  Name5    Chennai   32
   EmpID    Name   Location
0     11  Name11     Mumbai
1     12  Name12     Mumbai
2     13  Name13  Bangalore
   YearsOfService
0              10
1               5
2              17
3              12
4               7


In [7]:
pd.concat([employees1,employees2])

EmpID    Name   Location   Age
0      1   Name1       Pune  35.0
1      2   Name2  Bangalore  30.0
2      3   Name3  Bangalore  45.0
3      4   Name4    Chennai  40.0
4      5   Name5    Chennai  32.0
0     11  Name11     Mumbai   NaN
1     12  Name12     Mumbai   NaN
2     13  Name13  Bangalore   NaN

In [23]:
pd.concat([employees1,employees2],axis=1) ##column wise

EmpID   Name   Location  Age  EmpID    Name   Location
0      1  Name1       Pune   35   11.0  Name11     Mumbai
1      2  Name2  Bangalore   30   12.0  Name12     Mumbai
2      3  Name3  Bangalore   45   13.0  Name13  Bangalore
3      4  Name4    Chennai   40    NaN     NaN        NaN
4      5  Name5    Chennai   32    NaN     NaN        NaN

In [17]:
pd.concat([employees1,service],axis=1)## columns wise

EmpID   Name   Location  Age  YearsOfService
0      1  Name1       Pune   35              10
1      2  Name2  Bangalore   30               5
2      3  Name3  Bangalore   45              17
3      4  Name4    Chennai   40              12
4      5  Name5    Chennai   32               7

In [18]:
##append(row wise)
employees1.append(employees2)

C:\Users\Ankit Sharma\AppData\Local\Temp\ipykernel_6580\3542821248.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  employees1.append(employees2)


EmpID    Name   Location   Age
0      1   Name1       Pune  35.0
1      2   Name2  Bangalore  30.0
2      3   Name3  Bangalore  45.0
3      4   Name4    Chennai  40.0
4      5   Name5    Chennai  32.0
0     11  Name11     Mumbai   NaN
1     12  Name12     Mumbai   NaN
2     13  Name13  Bangalore   NaN

In [8]:
## Merge(column wise if there is any common element)
employees1.merge(employees2)
## no elements are common so no output

Empty DataFrame
Columns: [EmpID, Name, Location, Age]
Index: []

In [10]:
di={"EmpID":[1,2,3,4,5],"YearsofService":[10,5,17,12,7]}
service2=pd.DataFrame(di)
service2

EmpID  YearsofService
0      1              10
1      2               5
2      3              17
3      4              12
4      5               7

In [11]:
##merge
employees1.merge(service2)

EmpID   Name   Location  Age  YearsofService
0      1  Name1       Pune   35              10
1      2  Name2  Bangalore   30               5
2      3  Name3  Bangalore   45              17
3      4  Name4    Chennai   40              12
4      5  Name5    Chennai   32               7

In [24]:
##joins
pd.merge(employees1,service2,on='EmpID',how='left')

EmpID   Name   Location  Age  YearsofService
0      1  Name1       Pune   35              10
1      2  Name2  Bangalore   30               5
2      3  Name3  Bangalore   45              17
3      4  Name4    Chennai   40              12
4      5  Name5    Chennai   32               7

In [28]:
pd.merge(employees1,service2,on='EmpID',how='right')

EmpID   Name   Location  Age  YearsofService
0      1  Name1       Pune   35              10
1      2  Name2  Bangalore   30               5
2      3  Name3  Bangalore   45              17
3      4  Name4    Chennai   40              12
4      5  Name5    Chennai   32               7

In [29]:
pd.merge(employees1,service2,on='EmpID',how='inner')

EmpID   Name   Location  Age  YearsofService
0      1  Name1       Pune   35              10
1      2  Name2  Bangalore   30               5
2      3  Name3  Bangalore   45              17
3      4  Name4    Chennai   40              12
4      5  Name5    Chennai   32               7

In [30]:
pd.merge(employees1,service2,on='EmpID',how='outer')

EmpID   Name   Location  Age  YearsofService
0      1  Name1       Pune   35              10
1      2  Name2  Bangalore   30               5
2      3  Name3  Bangalore   45              17
3      4  Name4    Chennai   40              12
4      5  Name5    Chennai   32               7

In [26]:
pd.merge(employees1,employees2,on='EmpID',how='right')

EmpID Name_x Location_x  Age  Name_y Location_y
0     11    NaN        NaN  NaN  Name11     Mumbai
1     12    NaN        NaN  NaN  Name12     Mumbai
2     13    NaN        NaN  NaN  Name13  Bangalore

In [27]:
pd.merge(employees1,employees2,on='EmpID',how='left')

EmpID Name_x Location_x  Age Name_y Location_y
0      1  Name1       Pune   35    NaN        NaN
1      2  Name2  Bangalore   30    NaN        NaN
2      3  Name3  Bangalore   45    NaN        NaN
3      4  Name4    Chennai   40    NaN        NaN
4      5  Name5    Chennai   32    NaN        NaN

In [2]:
##Data preprocessing
import pandas as pd
df=pd.read_csv("C:/Users/Ankit Sharma/Desktop/python/rating.csv")
df

ID  PlaceID  Rating  Service_rating
0      1      123     5.0               3
1      2      234     NaN               3
2      3      345     NaN               4
3      4      231     1.0               5
4   Dup1       56     3.0               4
5   Dup1        2     3.0               3
6   Dup1       76     4.0               3
7      5      998     5.0               3
8      6     2345     4.0               4
9      7      764     5.0               5
10     8       77     3.0           99999
11     8       77     3.0               4
12     8       77     3.0               4
13     8       77     3.0               4
14     8       77     3.0               4

In [3]:
##check for null values
df.isnull()
## true represent no value is there

ID  PlaceID  Rating  Service_rating
0   False    False   False           False
1   False    False    True           False
2   False    False    True           False
3   False    False   False           False
4   False    False   False           False
5   False    False   False           False
6   False    False   False           False
7   False    False   False           False
8   False    False   False           False
9   False    False   False           False
10  False    False   False           False
11  False    False   False           False
12  False    False   False           False
13  False    False   False           False
14  False    False   False           False

In [ ]:
##to check missing value in particular columns

In [5]:
df.Rating

0     5.0
1     NaN
2     NaN
3     1.0
4     3.0
5     3.0
6     4.0
7     5.0
8     4.0
9     5.0
10    3.0
11    3.0
12    3.0
13    3.0
14    3.0
Name: Rating, dtype: float64

In [6]:
df.Rating.isnull()

0     False
1      True
2      True
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
Name: Rating, dtype: bool

In [9]:
##drop missing value: complete rows
df.dropna()

ID  PlaceID  Rating  Service_rating
0      1      123     5.0               3
3      4      231     1.0               5
4   Dup1       56     3.0               4
5   Dup1        2     3.0               3
6   Dup1       76     4.0               3
7      5      998     5.0               3
8      6     2345     4.0               4
9      7      764     5.0               5
10     8       77     3.0           99999
11     8       77     3.0               4
12     8       77     3.0               4
13     8       77     3.0               4
14     8       77     3.0               4

In [10]:
##Filling the null values
df.fillna("23")

ID  PlaceID Rating  Service_rating
0      1      123    5.0               3
1      2      234     23               3
2      3      345     23               4
3      4      231    1.0               5
4   Dup1       56    3.0               4
5   Dup1        2    3.0               3
6   Dup1       76    4.0               3
7      5      998    5.0               3
8      6     2345    4.0               4
9      7      764    5.0               5
10     8       77    3.0           99999
11     8       77    3.0               4
12     8       77    3.0               4
13     8       77    3.0               4
14     8       77    3.0               4

In [19]:
df.fillna("23")

ID  PlaceID     Rating  Service_rating
0      1      123        5.0               3
1      2      234  mangalpur               3
2      3      345         23               4
3      4      231        1.0               5
4   Dup1       56        3.0               4
5   Dup1        2        3.0               3
6   Dup1       76        4.0               3
7      5      998        5.0               3
8      6     2345        4.0               4
9      7      764        5.0               5
10     8       77        3.0           99999
11     8       77        3.0               4
12     8       77        3.0               4
13     8       77        3.0               4
14     8       77        3.0               4

In [4]:
df.Rating.mean

<bound method NDFrame._add_numeric_operations.<locals>.mean of 0     5.0
1     NaN
2     NaN
3     1.0
4     3.0
5     3.0
6     4.0
7     5.0
8     4.0
9     5.0
10    3.0
11    3.0
12    3.0
13    3.0
14    3.0
Name: Rating, dtype: float64>

In [20]:
##removing duplicates
df.duplicated()
##

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13     True
14     True
dtype: bool

In [21]:
df.drop_duplicates() ## delete duplicate rows complete

ID  PlaceID     Rating  Service_rating
0      1      123        5.0               3
1      2      234  mangalpur               3
2      3      345        NaN               4
3      4      231        1.0               5
4   Dup1       56        3.0               4
5   Dup1        2        3.0               3
6   Dup1       76        4.0               3
7      5      998        5.0               3
8      6     2345        4.0               4
9      7      764        5.0               5
10     8       77        3.0           99999
11     8       77        3.0               4

In [24]:
## replacing garbage value 
##1. replace by Nan first
import numpy as np
df1=df.replace(99999,np.nan)
df1
##other way: df["Service_rating"][10]="NaN"
##df

ID  PlaceID     Rating  Service_rating
0      1      123        5.0             3.0
1      2      234  mangalpur             3.0
2      3      345        NaN             4.0
3      4      231        1.0             5.0
4   Dup1       56        3.0             4.0
5   Dup1        2        3.0             3.0
6   Dup1       76        4.0             3.0
7      5      998        5.0             3.0
8      6     2345        4.0             4.0
9      7      764        5.0             5.0
10     8       77        3.0             NaN
11     8       77        3.0             4.0
12     8       77        3.0             4.0
13     8       77        3.0             4.0
14     8       77        3.0             4.0

In [29]:
df1.Service_rating.mean()
                    

3.7857142857142856

In [35]:
df1=df1.fillna(df1.Service_rating.mean())
df1

ID  PlaceID     Rating  Service_rating
0      1      123        5.0        3.000000
1      2      234  mangalpur        3.000000
2      3      345   3.785714        4.000000
3      4      231        1.0        5.000000
4   Dup1       56        3.0        4.000000
5   Dup1        2        3.0        3.000000
6   Dup1       76        4.0        3.000000
7      5      998        5.0        3.000000
8      6     2345        4.0        4.000000
9      7      764        5.0        5.000000
10     8       77        3.0        3.785714
11     8       77        3.0        4.000000
12     8       77        3.0        4.000000
13     8       77        3.0        4.000000
14     8       77        3.0        4.000000

In [ ]:
##date:19june
##Grouping

In [9]:
import pandas as pd
df=pd.read_csv("C:/Users/Ankit Sharma/Desktop/python/mtcars.csv")
df

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1   
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1   
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1   
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1   
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1   
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1  
26     5     2  
27     5     2  
28     5     4  
29     5     6  
30     5     8  
31     4     2

In [10]:
print(df.groupby('gear').groups)
## it make diff-diff groups for car having same gear.example: cars having 3,4,5,6,11,12,13.. index have 3 gear

{3: [3, 4, 5, 6, 11, 12, 13, 14, 15, 16, 20, 21, 22, 23, 24], 4: [0, 1, 2, 7, 8, 9, 10, 17, 18, 19, 25, 31], 5: [26, 27, 28, 29, 30]}


In [13]:
print(df.groupby('gear')["Unnamed: 0"].count())

gear
3    15
4    12
5     5
Name: Unnamed: 0, dtype: int64


In [15]:
print(df.groupby(['gear','carb']).count())

           Unnamed: 0  mpg  cyl  disp  hp  drat  wt  qsec  vs  am
gear carb                                                        
3    1              3    3    3     3   3     3   3     3   3   3
     2              4    4    4     4   4     4   4     4   4   4
     3              3    3    3     3   3     3   3     3   3   3
     4              5    5    5     5   5     5   5     5   5   5
4    1              4    4    4     4   4     4   4     4   4   4
     2              4    4    4     4   4     4   4     4   4   4
     4              4    4    4     4   4     4   4     4   4   4
5    2              2    2    2     2   2     2   2     2   2   2
     4              1    1    1     1   1     1   1     1   1   1
     6              1    1    1     1   1     1   1     1   1   1
     8              1    1    1     1   1     1   1     1   1   1


In [16]:
print(df.groupby(['gear','carb'])['mpg'].count()) ## print mpg column only

gear  carb
3     1       3
      2       4
      3       3
      4       5
4     1       4
      2       4
      4       4
5     2       2
      4       1
      6       1
      8       1
Name: mpg, dtype: int64


In [17]:
print(df.groupby(['gear','carb'])['mpg'].mean()) ## print mean of mpg column only

gear  carb
3     1       20.333333
      2       17.150000
      3       16.300000
      4       12.620000
4     1       29.100000
      2       24.750000
      4       19.750000
5     2       28.200000
      4       15.800000
      6       19.700000
      8       15.000000
Name: mpg, dtype: float64


In [11]:
print(df.groupby('am').groups)


{0: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 20, 21, 22, 23, 24], 1: [0, 1, 2, 17, 18, 19, 25, 26, 27, 28, 29, 30, 31]}

In [12]:
print(df.groupby('cyl').groups)

{4: [2, 7, 8, 17, 18, 19, 20, 25, 26, 27, 31], 6: [0, 1, 3, 5, 9, 10, 29], 8: [4, 6, 11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 28, 30]}


In [20]:
print(df.groupby(["am","vs"])['mpg'].mean())

am  vs
0   0     15.050000
    1     20.742857
1   0     19.750000
    1     28.371429
Name: mpg, dtype: float64
